export const HOME_URL = '/'
export const DASHBOARD_URL = '/dashboard'
export const LOGIN_URL = '/login'
export const COURIER_DASHBOARD_URL = '/courier-dashboard'
export const ORDERS_URL = '/orders'
export const TRACKING_URL = '/tracking'
